USE ECOMMERCE;

-- =========================================================
-- BAISC ANALYSIS
-- =========================================================
-- Q1: What is the total number of customers?
SELECT COUNT(*)TOTAL_CUSTOMERS FROM CUSTOMERS;

-- Q2: What is the total number of orders?
SELECT COUNT(*)TOTAL_ORDERS FROM ORDERS;

-- Q3: What is the total revenue generated by the business?
SELECT SUM(ORDER_AMOUNT)TOTAL_REVENUE FROM ORDERS;

-- Q4: What is the average order value (AOV)?
SELECT ROUND(AVG(ORDER_AMOUNT),2)AVG_ODV FROM ORDERS;

-- Q5: Which cities generate the highest revenue?
SELECT CITY,SUM(ORDER_AMOUNT)AS REVENUE
FROM CUSTOMERS AS C
JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CITY
ORDER BY REVENUE DESC;

-- =========================================================
-- CUSTOMER ANALYSIS
-- =========================================================-- 
-- Q6: How much has each customer spent in total?
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(O.ORDER_AMOUNT)AS TOTAL_SPENT
FROM CUSTOMERS AS C
JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

-- Q7: Who are the top 10 customers by total spending?
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,SUM(O.ORDER_AMOUNT)AS TOTAL_SPENT
FROM CUSTOMERS AS C
JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 10;

-- Q8: How many orders has each customer placed?
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,COUNT(O.ORDER_ID)AS TOTAL_ORDERS
FROM CUSTOMERS AS C
JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
ORDER BY TOTAL_ORDERS DESC;

-- Q9: Which customers have placed more than 5 orders?
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,COUNT(O.ORDER_ID)AS TOTAL_ORDERS
FROM CUSTOMERS AS C
JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
HAVING TOTAL_ORDERS >5
ORDER BY TOTAL_ORDERS DESC;

-- Q10: How can customers be segmented based on total spending?
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,
SUM(O.ORDER_AMOUNT)AS TOTAL_SPENT,
CASE 
	WHEN SUM(O.ORDER_AMOUNT)>=50000 THEN 'Premium'
    WHEN SUM(O.ORDER_AMOUNT)>=25000 THEN 'Gold' 
	ELSE 'Regular'
END AS CUSTOMER_SEGMENT
FROM CUSTOMERS AS C
JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

-- =========================================================
-- PRODUCT & CATEGORY ANALYSIS
-- =========================================================
-- Q11: Which product categories generate the most revenue?
select category,
sum(order_amount)revenue from orders as o
join order_items as oi
on o.order_id=oi.order_id
join products as p 
on oi.product_id=p.product_id
group by category
order by revenue desc;

-- Q12: Which products are sold the most (by quantity)?
select product_name,
sum(quantity)Total_qty from order_items as oi
join products as p 
on oi.product_id=p.product_id
group by product_name
order by Total_qty desc
limit 10;

-- Q13: Which products generate the highest revenue?
SELECT * FROM (
    SELECT 
        p.category,
        p.product_name,
        SUM(o.order_amount) AS revenue,
        ROW_NUMBER() OVER (
            PARTITION BY p.category
            ORDER BY SUM(o.order_amount) DESC
        ) AS rn
    FROM orders o
    JOIN order_items oi 
    ON o.order_id = oi.order_id
    JOIN products p 
    ON oi.product_id = p.product_id
    GROUP BY p.category, p.product_name
) t
WHERE rn = 1;

-- Q14: What is the top-performing product in each category?
select p.category,
count(distinct o.order_id)total_od
from orders as o
join order_items as oi
on o.order_id=oi.order_id
join products as p 
on oi.product_id=p.product_id
group by category
order by total_od desc;

-- Q15: How many orders are placed in each category?
WITH LATEST_ORDERS AS
(SELECT *,ROW_NUMBER()OVER(PARTITION BY CUSTOMER_ID
ORDER BY ORDER_DATE DESC) AS RN
FROM ORDERS) SELECT * FROM LATEST_ORDERS
WHERE RN=1;

-- =========================================================
-- ADVANCED CUSTOMER BEHAVIOR & REVENUE TREND ANALYSIS
-- =========================================================

-- Q16: What is the latest order placed by each customer?
WITH latest_orders AS (
    SELECT 
        o.customer_id,
        o.order_id,
        o.order_date,
        o.order_amount,
        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id 
            ORDER BY o.order_date DESC
        ) AS rn
    FROM orders AS o
)
SELECT *
FROM latest_orders
WHERE rn = 1;


-- Q17: How are customers ranked based on total spending?
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.order_amount) AS total_spent,
    RANK() OVER (
        ORDER BY SUM(o.order_amount) DESC
    ) AS rank_no
FROM orders AS o
JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY rank_no;


-- Q18: What is the time gap between consecutive orders for each customer?
SELECT 
    customer_id,
    order_date,
    COALESCE(
        DATEDIFF(
            order_date,
            LAG(order_date) OVER (
                PARTITION BY customer_id 
                ORDER BY order_date
            )
        ), 0
    ) AS gap_days
FROM orders;


-- Q19: Which customers show repeat purchase behavior?
SELECT 
    customer_id,
    order_date,
    CASE 
        WHEN DATEDIFF(
            order_date,
            LAG(order_date) OVER (
                PARTITION BY customer_id 
                ORDER BY order_date
            )
        ) <= 20 THEN 'Repeat'
        ELSE 'New/Inactive'
    END AS customer_type
FROM orders;


-- Q20: How does cumulative revenue grow over time?
SELECT 
    order_date,
    SUM(order_amount) OVER (
        ORDER BY order_date
    ) AS running_revenue
FROM orders;


-- Q21: Which orders are above the customer's average order value?
SELECT *
FROM (
    SELECT 
        customer_id,
        order_id,
        order_amount,
        ROUND(
            AVG(order_amount) OVER (
                PARTITION BY customer_id
            ), 2
        ) AS avg_order
    FROM orders
) AS t
WHERE order_amount > avg_order;

